name: 'Org Automation CI'
on:
  pull_request:
    paths:
      - 'org/*.py'
      - 'org/requirements*'
      - 'org/pyproject.toml'
      - '.github/workflows/org-management-ci.yml'
jobs:
  org-automation-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - uses: actions/checkout@v4
        with:
          path: community
      - name: pip install
        run: |
          python -m pip install --upgrade pip
          pip install -r community/org/requirements.txt
          pip install -r community/org/requirements-dev.txt
      - name: flake8 and black
        run: |
          cd community/org
          python -m flake8
      - name: unit tests
        run: |
          cd community/org
          python -m unittest discover -s .
